default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: annapetry
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/dangThang_development

production:
  <<: *default
  database: db/dangThang_production
